name: Release

on:
  push:
    tags:
      - '*.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Report PHP version
        run: php -v

      - name: composer
        run: composer install --no-interaction

      - name: NPM
        run: npm install; npm run build;

      - name: Build project
        run: |
          mkdir disciple-tools-tree-fixer
          cp -r disciple-tools-tree-fixer.php admin dist languages rest-api vendor spinner.svg version-control.json LICENSE SECURITY.md readme.md disciple-tools-tree-fixer/
          zip -r disciple-tools-tree-fixer.zip disciple-tools-tree-fixer
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./disciple-tools-tree-fixer.zip
          asset_name: disciple-tools-tree-fixer.zip
          asset_content_type: application/zip
